#!/usr/bin/python
import sys
import pprint

def usage():
	print "usage: {} <filename>".format(sys.argv[0])
	raise SystemExit(0)

def process_cdr(cdr):
	try:
		print "process {}: {}@{}:{} -> {}@{}:{}".format(cdr['start_time'],cdr['src_prefix_in'],cdr['legA_remote_ip'],cdr['legA_remote_port'],cdr['dst_prefix_in'],cdr['legA_local_ip'],cdr['legA_local_port'])
		#TODO: we should write cdr into database here
	except:
		print "exception occured"

if len(sys.argv) < 2:
	usage()

#TODO: connect to database here

with open(sys.argv[1],'r') as f:
	p = pprint.PrettyPrinter(indent=4)
	fields = []
	info = {}
	nf = 1
	cdrs_count = 0
	for l in f:
		if l[0]=='#':
			l = l.lstrip('#').rstrip()
			[name,val] = l.split(": ")
			if name == "fields_descr":
				for f in val.split(','):
					fields.append(f.rstrip("'").lstrip("'"))
			else:
				info[name] = val
		else:
			if nf:
				p.pprint(info)
				print "\ncdr_fields: {}\n\n".format(fields)
				#TODO: prepare db query here
				nf = 0	
			#pasrse cdr line
			cdr = {}
			for i,fld in enumerate(l.split(',')):
				fld = fld.rstrip("'").lstrip("'")
				cdr[fields[i]] = fld
			process_cdr(cdr)
			cdrs_count+=1
	print "\nprocessed: {}".format(cdrs_count)	
