#!/bin/sh

#DEBHELPER#

if [ "$1" = "purge" ] ; then
  # remove user/group on purge
  deluser --quiet --remove-home sems &>/dev/null || true
  # remove /etc/ser if empty
  rmdir /etc/sems || true
fi

if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
  invoke-rc.d rsyslog restart 3>/dev/null || exit 0
else
  /etc/init.d/rsyslog restart 3>/dev/null || exit 0
fi

exit 0

